export const ROLE_NAME_USER='USER';
export const ROLE_NAME_EMPLOYEE='EMPLOYER';
export const ROLE_NAME_ADMIN='ADMIN';
export const TAB_CANDIDATE='CANDIDATE';
export const TAB_JOB='JOB';
export const TAB_SKILL='SKILL';
export const TAB_LEVEL='LEVEL';
export const PROMOTE_JOB='PROMOTE_JOB';
export const VIEW_DETAIL='VIEW_DETAIL';
export const VIEW_DETAIL_APPLICATION='VIEW_DETAIL_APPLICATION';
export const MARK_AS_EXPIRED='MARK_AS_EXPIRED';
export const MY_JOB_HOME='HOME';
export const TAB_JOB_TYPE = 'JOB_TYPE';
export const TAB_JOB_CONTRACT_TYPE = 'TAB_JOB_CONTRACT_TYPE';
export const TAB_DEGREE_TYPE = 'TAB_DEGREE_TYPE';
export const TAB_CURRENCY_TYPE = 'TAB_CURRENCY_TYPE';



