name: Hire Dev

on: 
    push:
      branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploying Hire Dev
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: 22
        script: |
          cd /home/ubuntu/Frontend-Hiring
          git fetch origin
          git checkout production
          git pull
          npm install --legacy-peer-deps
          npm run build
